export * from './empresa.repository';
export * from './obligacion.repository';
export * from './documento.repository';
export * from './user.repository';
export * from './obligacion-fecha.repository';
export * from './empresa-obligacion.repository';
export * from './documento-categoria.repository';
export * from './obligacion-anio.repository';
export * from './recover-password.repository';
