/**
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * (Schema options: { partial: true })
 */
export interface EmpresaPartial {
  id?: number;
  nombre?: string;
  tipo?: number;
  nit?: string;
  contacto?: string;
  direccion?: string;
  email?: string;
  telefono?: string;
  cedula?: string;
  claveDian?: string;
  claveFirmaDian?: string;
  placeIyc?: string;
  placaReteica?: string;
  datosContabilidad?: string;
  userId?: number;
}
