/**
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface EmpresasFields {
  id?: boolean;
  nombre?: boolean;
  tipo?: boolean;
  nit?: boolean;
  contacto?: boolean;
  direccion?: boolean;
  email?: boolean;
  telefono?: boolean;
  cedula?: boolean;
  claveDian?: boolean;
  claveFirmaDian?: boolean;
  placeIyc?: boolean;
  placaReteica?: boolean;
  datosContabilidad?: boolean;
  userId?: boolean;
}
