/**
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse2001Headers } from './inlineResponse2001Headers';

export interface InlineResponse2001 {
  greeting?: string;
  date?: string;
  url?: string;
  headers?: InlineResponse2001Headers;
}
