/**
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * (Schema options: { partial: true })
 */
export interface ObligacionPartial {
  id?: number;
  nombre?: string;
  digitos?: number;
  periodicidad?: number;
  tipo?: number;
}
